window.playerTmpStore=window.playerTmpStore||[];
(function(g,k,l){var h={propagateErrorSafely:function(a){g.setTimeout(function(){throw a;},0)},dom:{getElementsByClassName:function(){return k.getElementsByClassName?k.getElementsByClassName:function(a,c,b,d){b=[];for(d in c=this.all)(c[d].className||"").match(a.replace(/(\S+) */g,"(?=(^|.* )$1( |$))"))&&b.push(c[d]);return b}}(),extractDataAttributes:function(a){var c=/^data\-([\w\W]+)$/;a=a?a.attributes||[]:[];var b={},d,e,f,g;g=0;for(f=a.length;g<f;g+=1)d=a[g],e=d.value||d.nodeValue,d=d.name||
d.nodeName,c.test(d)&&(b[d.replace("data-","")]=e);return b},addEventListener:function(){var a;g.addEventListener?a=function(a,b,d){window.playerTmpStore[a]||(window.playerTmpStore[a]=!0,d.addEventListener(a,b,!1))}:g.attachEvent&&(a=function(a,b,d){window.playerTmpStore[a]||(window.playerTmpStore[a]=!0,d.attachEvent("on"+a,b))});return a}(),getViewportMeta:function(){var a=k.getElementsByTagName("meta"),c,b,d,e;e=0;for(b=a.length;e<b;e+=1)if((c=a[e].getAttribute("name"))&&"viewport"===c){d=a[e];
break}h.getViewportMeta=function(){return d};return d}},hacks:{percentualFrameDimension:function(a,c){var b=c,d;l.userAgent.match(/iPhone|iPad|iPod/i)&&("height"===a||"width"===a)&&c&&(d={height:k.documentElement.clientHeight,width:k.documentElement.clientWidth},-1<c.indexOf("%")&&(b=parseInt(c,10),b=(b/100*d[a]).toString()));return b}}},q=function(a,c){var b,d="http://gameplayer.io/",e=g.encodeURIComponent(k.location.protocol+"//"+k.location.host),f=function(a,e){a&&(a=h.hacks.percentualFrameDimension("width",
a),0>a.indexOf("%")?c.style.width=a+"px":c.style.width=a,b.width=a);e&&(e=h.hacks.percentualFrameDimension("height",e),0>e.indexOf("%")?c.style.height=e+"px":c.style.height=e,b.height=e)},n=function(c,e){if(b&&b.contentWindow){var d={mssg:c,gid:a.gid};e&&(d.data=e);b.contentWindow.postMessage(d,b.src)}};a.sub&&""!==a.sub&&(d="loc"===a.sub?d+".loc":"http://"+a.sub+".gameplayer.io");(function(){var h=d+"/embed/"+a.gid+"/?ref="+e,l=["monetize","theme","preview-url","preview-integration-type"],n=l.length,
p,m;for(m=0;m<n;m+=1)p=l[m],a.hasOwnProperty(p)&&(h+="&"+p.replace(/\-/g,"_")+"="+g.encodeURIComponent(a[p]));b=k.createElement("iframe");f(a.width,a.height);b.setAttribute("seamless","true");b.setAttribute("webkitAllowFullScreen","true");b.setAttribute("mozallowfullscreen","true");b.setAttribute("allowFullScreen","true");b.setAttribute("webkit-playsinline","true");b.setAttribute("frameBorder","0");b.setAttribute("scrolling","no");b.setAttribute("name","gameplayer-"+a.gid);b.style.margin="0";b.style.padding=
"0";b.style.border="0";b.setAttribute("src",h);c.appendChild(b)})();return{sendAuthToken:function(a){n("game.reply.auth",'{"token":"'+a+'"}')},sendPong:function(){n("pong")},settings:a,onOrientationChange:function(){b&&b.contentWindow&&(l.userAgent.match(/iPhone|iPad|iPod/i)&&(f(a.width,a.height),window.scrollTo(0,0)),b.contentWindow.postMessage({mssg:"orientationchange",gid:a.gid},b.src))},onDeviceOrientation:function(c){b&&b.contentWindow&&b.contentWindow.postMessage({mssg:"deviceorientation",gid:a.gid,
event:c},b.src)}}};(function(){var a={};return g.GamePlayerFactory={getPlayers:function(){return a},start:function(){var c,b,d,e;c=h.dom.getElementsByClassName.call(k,"gameplayer");e=0;for(d=c.length;e<d;e+=1){b=h.dom.extractDataAttributes(c[e]);try{b.gid&&(a[b.gid]=new q(b,c[e]))}catch(f){h.propagateErrorSafely(f)}}}}})();var r=function(a){"function"===typeof a&&(h.dom.addEventListener("message",function(c){a(c)},g),h.dom.addEventListener("orientationchange",function(){a({data:{gid:"all",mssg:"orientationchange"}})},
g),h.dom.addEventListener("deviceorientation",function(c){a({data:{gid:"all",mssg:"deviceorientation",event:c}})},g))},t=function(a){a=("; "+k.cookie).split("; "+a+"=");if(2==a.length)return a.pop().split(";").shift()},f=function(){var a={},c=a.hasOwnProperty;return{subscribe:function(b,d){c.call(a,b)||(a[b]=[]);var e=a[b].push(d)-1;return{remove:function(){delete a[b][e]}}},publish:function(b,d){if(!c.call(a,b))return!1;var e,f;f=0;for(e=a[b].length;f<e;f+=1)(0,a[b][f])(d||{})}}}(),u=function(a){var c=
a.data,b;if("string"===typeof a.data)try{c=JSON.parse(a.data)}catch(d){}if(a&&c&&"object"===typeof c&&c.gid)if(a=g.GamePlayerFactory.getPlayers(),"all"===c.gid)for(b in a){if(a.hasOwnProperty(b))switch(c.mssg){case "orientationchange":a[b].onOrientationChange();break;case "deviceorientation":a[b].onDeviceOrientation({alpha:c.event.alpha,beta:c.event.beta,gamma:c.event.gamma})}}else switch(b=a[c.gid],c.mssg){case "game.request.auth":b&&b.sendAuthToken(t("token"));break;case "ping":b&&b.sendPong();
break;case "updateViewport":b&&"true"===b.settings["use-viewport"]&&(b=h.dom.getViewportMeta())&&b.setAttribute("content",c.content);break;case "game.update.highscore":case "game.update.highscore.failed":f.publish("highscore.update",JSON.parse(c.data));break;case "game.update.achievement":case "game.update.achievement.failed":f.publish("achievement.update",JSON.parse(c.data));break;case "game.display":f.publish("game.display",JSON.parse(c.data));break;case "game.start":f.publish("game.start",JSON.parse(c.data));
break;case "game.pause":f.publish("game.pause",JSON.parse(c.data));break;case "game.continue":f.publish("game.continue",JSON.parse(c.data));break;case "game.mute":f.publish("game.mute",JSON.parse(c.data));break;case "game.gameBreak":f.publish("game.gameBreak",JSON.parse(c.data));break;case "game.end":f.publish("game.end",JSON.parse(c.data));break;case "game.flashdetection":f.publish("game.flashdetection",JSON.parse(c.data))}};(function(){var a,c,b="function"===typeof g.GamePlayerAPI?g.GamePlayerAPI():
g.GamePlayerAPI||[],d={onGameDisplay:function(a){f.subscribe("game.display",a)},onGameStart:function(a){f.subscribe("game.start",a)},onGamePause:function(a){f.subscribe("game.pause",a)},onGameContinue:function(a){f.subscribe("game.continue",a)},onGameMute:function(a){f.subscribe("game.mute",a)},onGameBreak:function(a){f.subscribe("game.gameBreak",a)},onScoreBroadCast:function(a){f.subscribe("game.scoreBroadCast",a)},onScoreSubmit:function(a){f.subscribe("highscore.update",a)},onGameEnd:function(a){f.subscribe("game.end",
a)},onFlashDetect:function(a){f.subscribe("game.flashdetection",a)}};c=0;for(a=b.length;c<a;c+=1)if(2===b[c].length&&d.hasOwnProperty(b[c][0]))d[b[c][0]](b[c][1]);b=[];return g.GamePlayerAPI=function(a,b){if(a&&b&&d.hasOwnProperty(a))d[a](b);return[]}})();try{window.postMessage&&r(u)}catch(v){h.propagateErrorSafely(v)}g.GamePlayerFactory.start()})(window,window.document,window.navigator);
